# Generated by Django 4.2.4 on 2023-10-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_is_admin_customuser_is_superadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(upload_to='images/profilepictures/'),
        ),
    ]
