# Generated by Django 4.2.4 on 2023-10-26 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='Book',
            new_name='book',
        ),
    ]
