# Generated by Django 4.2.4 on 2023-10-19 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('slug', models.SlugField(max_length=100, null=True, unique=True)),
                ('Picture', models.ImageField(null=True, upload_to='images/authors/Pictures')),
                ('about_author', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=100, null=True)),
                ('slug', models.SlugField(max_length=100, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('edition', models.CharField(max_length=10)),
                ('Date_Published', models.DateField()),
                ('Number_of_Pages', models.IntegerField()),
                ('Date_of_Upload', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=100, null=True, unique=True)),
                ('Picture', models.ImageField(upload_to='images/books/')),
                ('About_Book', models.TextField()),
                ('is_available', models.BooleanField(default=True)),
                ('Price', models.IntegerField(null=True)),
                ('Genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookapp.genre')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookapp.authors')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
    ]
