# Generated by Django 4.2.4 on 2023-11-02 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_books_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='uploader',
        ),
    ]
